apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: send
spec:
  source: email.jobs
  destination: email.send
  destinationType: queue
  routingKey: send
  rabbitmqClusterReference:
    name: rabbitmq
