email:
  resend:
    api_key: "${RESEND_API_KEY}"

transport:
  http:
    address: "0.0.0.0:8011"
    timeout: 10s

  grpc:
    address: "0.0.0.0:9011"
    timeout: 10s

  rabbitmq:
    address: "amqp://rabbitmq:5672"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    queues:
      send_email: email.send-email

data:
  mysql:
    dsn: "${MYSQL_DSN}"
    max_open_connections: 50
    max_idle_connections: 10
    max_connection_lifetime: 1800s

observability:
  tracing:
    protocol: PROTOCOL_HTTP_PROTOBUF
    endpoint: https://otlp-gateway-prod-ap-southeast-2.grafana.net/otlp/v1/traces
    authorization: "${OBSERVABILITY_AUTHORIZATION}"
    sample_ratio: 0.1

  metrics:
    protocol: PROTOCOL_HTTP_PROTOBUF
    endpoint: https://otlp-gateway-prod-ap-southeast-2.grafana.net/otlp/v1/metrics
    authorization: "${OBSERVABILITY_AUTHORIZATION}"
    export_interval: 5s
