apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: email.jobs
spec:
  name: email.jobs
  type: direct
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
