apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: email-config
    files:
      - config.yaml

secretGenerator:
  - name: email-secret
    envs:
      - secret.env
