# Main
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: email.send-email
spec:
  name: email.send-email
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
---
# DLQ
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: email.send-email.dlq
spec:
  name: email.send-email.dlq
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
