# Main
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: asset
spec:
  name: asset
  type: direct
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
---
# DLQ
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: asset.dlx
spec:
  name: asset.dlx
  type: direct
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
