# Main
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.create
spec:
  name: asset.image.create
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.reconcile
spec:
  name: asset.image.reconcile
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.process
spec:
  name: asset.image.process
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq

---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.delete
spec:
  name: asset.image.delete
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq

---
# DLQ
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.delete.dlq
spec:
  name: asset.image.delete.dlq
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.create.dlq
spec:
  name: asset.image.create.dlq
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.reconcile.dlq
spec:
  name: asset.image.reconcile.dlq
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: asset.image.process.dlq
spec:
  name: asset.image.process.dlq
  type: quorum
  durable: true
  autoDelete: false
  rabbitmqClusterReference:
    name: rabbitmq
