apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafbat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafbat-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafbat-ui
    spec:
      containers:
        - name: kafbat-ui
          image: ghcr.io/kafbat/kafka-ui:v1.5.0
          ports:
            - name: http
              containerPort: 18080
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "18080"

            - name: KAFKA_CLUSTERS_0_NAME
              value: velony

            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-kafka-bootstrap:9092

            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
              value: debezium

            - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
              value: http://debezium-connect:8083

            - name: KAFKA_CLUSTERS_0_READONLY
              value: "true"
