apiVersion: v1
kind: Service
metadata:
  name: kafbat-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafbat-ui
  ports:
    - name: management
      appProtocol: http
      protocol: TCP
      port: 18080
      targetPort: 18080
