apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium
  annotations:
    strimzi.io/use-connector-resources: "true"

spec:
  replicas: 1

  bootstrapServers: kafka-kafka-bootstrap:9092

  groupId: debezium-group
  configStorageTopic: debezium-configs
  offsetStorageTopic: debezium-offsets
  statusStorageTopic: debezium-status

  template:
    pod:
      imagePullSecrets:
        - name: ghcr-pull

    buildContainer:
      securityContext:
        privileged: true

  build:
    output:
      type: docker
      image: ghcr.io/velonyapp/debezium:latest
      pushSecret: ghcr-push

    plugins:
      - name: debezium-mysql
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/3.5.0.Final/debezium-connector-mysql-3.5.0.Final-plugin.tar.gz

      - name: debezium-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/3.5.0.Final/debezium-connector-postgres-3.5.0.Final-plugin.tar.gz

      - name: debezium-oracle
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-oracle/3.5.0.Final/debezium-connector-oracle-3.5.0.Final-plugin.tar.gz

          - type: jar
            url: https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc11/23.26.0.0.0/ojdbc11-23.26.0.0.0.jar

  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider

    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
