apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker

  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 15Gi
        class: local-path
        deleteClaim: false
        kraftMetadata: shared
